export const bestSellingProductData = [
  {
    id: 1,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/NorthCoat.svg",
    description: "The north coat",
    amount: ["$120", "$160"],
    stars: 5,
    rating: 65,
  },
  {
    id: 2,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/GucciBag.svg",
    description: "Gucci duffle bag",
    amount: ["$120", "$160"],
    stars: 4,
    rating: 65,
  },
  {
    id: 3,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/LiquidCpuCooler.svg",
    description: "RGB liquid CPU Cooler",
    amount: ["$120", "$160"],
    stars: 5,
    rating: 75,
  },
  {
    id: 4,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/SmallBookShop.svg",
    description: "Small BookSelf",
    amount: ["$120", "$160"],
    stars: 4,
    rating: 75,
  },
];
