export const exploreOurProductData = [
  {
    id: 1,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/DryDoogFood.svg",
    description: "Breed Dry Dog Food",
    amount: "$120",
    stars: "/images/Five star.svg",
    rating: 35,
  },
  {
    id: 2,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/Camera.svg",
    description: "CANON EOS DSLR Camera",
    amount: "$120",
    stars: "/images/Five star.svg",
    rating: 95,
  },
  {
    id: 3,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/GamingLaptop.svg",
    description: "ASUS FHD Gaming Laptop",
    amount: "$120",
    stars: "/images/Five star.svg",
    rating: 325,
  },
  {
    id: 4,
    heart: "/images/HeartIcon.svg",
    quickVeiw: "/images/Quick View.svg",
    image: "/images/product-set.png",
    description: "Curology Product Set ",
    amount: "$120",
    stars: "/images/Five star.svg",
    rating: 145,
  },
];